### ISSUE TITLE
【誤記】組み立てマニュアル2.4.7のC6実装の写真(青枠)がC7を示している＆2.4.8のチップコンデンサ一覧(青枠)に漏れがある

### ISSUE THREAD

**Issue by y-ohe** [algyan/XIAOGYAN#53]
組み立てマニュアル2.4.7のC6実装の写真(青枠)がC7を示しています。
C6の場所はスピーカとボリュームの間の下側パッドになります。
青枠の位置を修正した写真に差し替えが必要です。
さらに、2.4.8のチップコンデンサの実装確認の写真において、C3、C4、C5、**C7**のみが青枠で囲まれていて、誤記があります。
正しくは、**C1**、**C2**、C3、C4、C5、**C6** を青枠で囲む必要があります。（C7は間違い！）

**Comment by tatsu1225** [comment]
ありがとうございます．修正してプルリクを投げました！
https://github.com/algyan/XIAOGYAN/pull/54#issue-1722322287

**Comment by yamati-kz** [comment]
@2.4.8のチップコンデンサ一覧(青枠)に漏れがある

C1とC2の青枠が漏れています。他は囲われています。

**Comment by matsujirushi** [comment]
@tatsu1225 確認お願いしますー

**Comment by tatsu1225** [comment]
@matsujirushi 承知です．確認します
@yamati-kz ご指摘ありがとうございます！青枠漏れてますね．というわけでサクッと修正しました．また何か気になる点などあればぜひ指摘頂ければと思います
https://github.com/algyan/XIAOGYAN/commit/f8f1ed80d11305f96bade13c57993fa9a335cee9

**Comment by yamati-kz** [comment]
@tatsu1225 早々のご対応ありがとうございました。青枠の追記を確認いたしました。
