### ISSUE TITLE
ES基板のIssue

### ISSUE THREAD

**Issue by matsujirushi** [algyan/XIAOGYAN#6]
## 動作確認

- [x] LEDマトリックス（黄色、3.3V）
- [x] LEDマトリックス（2色、3.3V）
- [x] スピーカー
- [x] エンコーダー
- [x] LED
- [x] ボタン
- [x] Grove I2C

### LEDマトリックス

- [ ] U2のパッド幅が小さい？
- [x] C1がU2に近すぎる
- [x] C1=10u(P-13161)
- [x] C1のパッドが大きすぎる
- [x] R1=100K
- [x] R2=100K

### スピーカー

- [x] C5のパッドが大きすぎる
- [x] R5=0
- [x] C6のパッドが大きすぎる
- [x] C3=DNP
- [x] VR1=10K
- [ ] パワーアンプENABLE時に破裂音がする（ https://github.com/algyan/algyan_8th/discussions/14 ）

### ロータリーエンコーダー

- [x] R8=DNP
- [x] R9=DNP
- [x] R10=0
- [x] R11=0
- [x] C7=DNP
- [x] C8=DNP

### LED

- [x] LED1=I-11580 + I-00641
- [x] R12=10K（ちょっと暗いけど、部品種類を減らすためにこれ）
- [x] リセット直後、LED1が点灯してしまう（U0TXDはリセット直後、output enabled, pull-up registor enabled）
- [x] LED1をアクティブLOWに変更（ https://github.com/algyan/algyan_8th/issues/6#issuecomment-1367884332 ）→ES2を改修

### ボタン

- [x] R13=DNP
- [x] R14=DNP
- [x] ボタンはアクティブLOWに変更（U1.D9はBOOTボタンと併用で、10Kでプルアップされている（ https://github.com/algyan/algyan_8th/issues/6#issuecomment-1366648034 ））→ES2を改修
- [ ] **ES基板のU9は実装するな！**（BOOTボタンと同時押しすると3V3-GND貫通）

### Grove I2C

- [x] C9=10u(P-13161)
- [x] 省電力向けの電源カット回路を忘れてた
  * 電源カット回路は改造して遊んでもらう事項に

### その他

- [x] JP3の下に、不要なVIA

**Comment by matsujirushi** [comment]
### LEDマトリックス

**SCLK:**

![image](https://user-images.githubusercontent.com/8079404/209455494-260ffa85-5153-45df-a39d-17597881723f.png)

**GRID1:**

![image](https://user-images.githubusercontent.com/8079404/209455504-97e1fdc3-4f46-44f3-8902-e42168500b73.png)
![image](https://user-images.githubusercontent.com/8079404/209455506-807d0904-66a6-4580-8dd7-4073dc069de4.png)

**Comment by tatsu1225** [comment]
ES1基板を頂きましたので，とりま手持ちの部品で可能な所まで組み立てました．
・VRの抵抗値はいくつがベターですか？-VINを0～1.15Vで変化させたいと思われましたので，とりあえず10K～100KでOKですかね？
・チップ抵抗・コンデンサの大きさは，0603/0804だと初学者には厳しそうｗ が，あえて小さいパーツで楽しんでもらうという趣向であればOKだと思いました 

![PXL_20221227_162340886](https://user-images.githubusercontent.com/7766952/209693910-58ab4b8a-09d3-458c-a26a-eed523b636ae.jpg)

**Comment by matsujirushi** [comment]
@tatsu1225 

> VRの抵抗値はいくつがベターですか？

記入漏れていました。ご指摘ありがとうございます。手元は**VR1=10K**にしています。（ https://github.com/algyan/algyan_8th/issues/6#issue-1510063566 に追加しました）

> チップ抵抗・コンデンサの大きさは，0603/0804だと初学者には厳しそうｗ

入手性考えると、リード部品かチップ部品1608(mm)と思いますが、手元在庫が1608なのでw
Discussionページ立てました。
https://github.com/algyan/algyan_8th/discussions/10

**Comment by tatsu1225** [comment]
あー、eagleだとinch表記で表示されるんで0603(1608(mm))すね。ふだん、チップ抵抗使わないので勘違いしとりました🙇(お恥ずかしい、pad見ればわかるやん😇

**Comment by matsujirushi** [comment]
@tatsu1225 
あるあるですねw（インチ<->ミリ）

あと、LEDマトリックスは2種類を動かしてみた感触では、2色のほうが良さそうなのでそちらを採用しようと思っています。（フットプリントはコスト上がらないので両方用意）

1. そちらで使っているボタンの通販コード、教えてもらえませんか？（秋月じゃない？）
2. XIAO SAMD21ってことは、もしかしてスピーカー辺りを試してくれようとしている？😍

**Comment by tatsu1225** [comment]
LEDマトリックスは2色ありだと思います。弊学でも(別の先生が)実習で使っている様子を見てますが、表現の幅が広がる印象持ってます。

タクトスイッチは秋月ですが10個パックです。
通販コードは P-02561

XIAO ESP32の手持ちが尽きてしまったので、ひとまず無印XIAOを刺してみただけ。なんて言えない😇
(スピーカーは同じものが手元にない&秋月も年末年始モードなので、 P-12494 でひとまず試してみようかと。

**Comment by matsujirushi** [comment]
### U1.D7はPULLDOWNできるが、U1.D9はPULLDOWNできない

* U1.D7 ... ESP32C3のPin27(U0RXD)
* U1.D9 ... ESP32C3のPin15(GPIO9) - BOOTボタンにも接続、BOOTボタンが10Kでプルアップされている。

**Comment by matsujirushi** [comment]
### LED1をアクティブLOWに変更

1. LED1のアノードとカソードを反対にする（R12側がアノード）
2. R12を左パッドだけに付ける
3. R12の空き側を3V3に接続

![image](https://user-images.githubusercontent.com/8079404/210068537-9259d047-fad8-4a74-98e2-681a91ca9e46.png)

**Comment by matsujirushi** [comment]
### パワーアンプENABLEの効果

DISABLEにすると、2.78mA -> 167uAに下がる。（つまり、効果あり）

![image](https://user-images.githubusercontent.com/8079404/210070095-06c64f2b-e710-410b-853a-d4926638a36d.png)

**Comment by matsujirushi** [comment]
### Grove I2Cの波形

ちょっと立ち上がりが遅いのが気になるけど、Groveモジュール側の話なので、、、問題ないと判断。

![image](https://user-images.githubusercontent.com/8079404/210136346-2f1dff40-6ba2-4322-a6e2-d0b1ecbe453b.png)

**Comment by tatsu1225** [comment]
・JP4のピンヘッダは実装＆ショートジャンパ必須
→ 3.3Vが各回路へ供給されない．どうも電流計測用のジャンパとのこと
　 ES2では削除予定(と聞きました
・以下のサンプルの動作確認ができました:-)
　－ButtonAndLed
　－Encoder
　－LedMatrixTM1640
　－Speaker2

**Comment by matsujirushi** [comment]
> JP4のピンヘッダは実装＆ショートジャンパ必須

PADにして、デフォルトをショートにしました。

![image](https://user-images.githubusercontent.com/8079404/216202440-925651cc-ad29-4a6b-bf30-10865b5c9514.png)
