### ISSUE TITLE
組み立てマニュアル Groveコネクタのはんだ付け

### ISSUE THREAD

**Issue by matsujirushi** [algyan/XIAOGYAN#61]
### Discussed in https://github.com/algyan/XIAOGYAN/discussions/58

<div type='discussions-op-text'>

<sup>Originally posted by **shoko93** June 11, 2023</sup>
Issueに書くか迷いましたがひとまずこちらに投稿しておきます。
組み立てマニュアルの2.5.4. Groveコネクタのはんだ付けについて。
秋月で購入したＬ型のGroveコネクタの場合そのままだと↓の写真の通りにはならないので、少し迷いました。
![image](https://github.com/algyan/XIAOGYAN/assets/9836975/fcfac116-d6eb-42db-a4e6-6ea24b4b6fb8)
（私の場合はよくわからなかったので、L字の足を無理やりまっすぐにしました。。）</div>

**Comment by tatsu1225** [comment]
これは私のやらかしですね．誤ってI字のGroveコネクタで実装してしまったようです．
全部の写真の差し替えは難しいですが，指摘頂いた箇所については撮影して修正します

**Comment by tatsu1225** [comment]
こんな感じでどうでしょう？
![img75](https://github.com/algyan/XIAOGYAN/assets/7766952/b617ef79-e138-4466-858c-05b160f89683)
