### ISSUE TITLE
2023/8/5現在 秋月電子でNJM2113Dが売り切れ中です

### ISSUE THREAD

**Issue by yak1ex** [algyan/XIAOGYAN#68]
その結果、「秋月電子通商 部品を買い物かごに入れる」のリンクを踏むと以下の表示が出ます。

![image](https://github.com/algyan/XIAOGYAN/assets/820530/c7639bde-eeb3-464d-9418-f1ad4ead9119)

別店舗での購入以外の手段としては、
* 回路図、部品表、基板を参照したところNJM2113M(I-10981)での代替を想定されているということでよろしいでしょうか？(※こちらも通販在庫数：12ですが)
* またこちらは自己責任かもしれませんがピン互換と思われるMC34119(I-17430)での対応もありでしょうか？ ref. http://tmj114.web.fc2.com/amp/miniamp.html

**Comment by matsujirushi** [comment]
情報ありがとうございます！

* 代わりに、`NJM2113M(I-10981)`でもOKです。
* `MC34119(I-17430)`は未確認です。

（だれか`MC34119(I-17430)`で試したら、結果を教えてください...）

**Comment by yamati-kz** [comment]
違和感ないです・MC34119(I-17430)を試しましたが聴いた感じでは...
本来の部品リスト上、NJM2113D(I-11192がが在庫不足ということで代替を試してみました。石が代わってもそれなりに動くのかなと思いつつ。オシロで違いを明示できればいいのですが、そんな技術者なく...
HardwareTest.binで試しています。平ピンICソケットなので載せ替えはすぐにできます。

**Comment by yamati-kz** [comment]
・ご参考になるかわかりませんがオシロで波形を取ってみました。
 　　　部品リスト品 : [NJM2113D(I-11192)](https://akizukidenshi.com/catalog/g/gI-11192/)
　　　代替候補品 : [MC34119(I-17430)](https://akizukidenshi.com/catalog/g/gI-17430/)

・IC PinNo.8(VOUT2)とGND間の波形です。ボリュームはMAX(右側に回し切った状態)。

・NJM2113DでボタンＡを押したとき。
![NJM2113D(I-11192)_ButtonA](https://github.com/algyan/XIAOGYAN/assets/135952435/166f99d0-dc1d-4c48-9aa1-aa5a77688447)

・NJM2113DでボタンBを押したとき。
![NJM2113D(I-11192)_ButtonB](https://github.com/algyan/XIAOGYAN/assets/135952435/f3934fe2-db95-4b98-b1b6-1b45b16f0025)

・MC34119でボタンＡを押したとき。
![MC34119(I-17430)_ButtonA](https://github.com/algyan/XIAOGYAN/assets/135952435/ae6c64a2-f7a7-4536-8910-9f662f9f0880)

・MC34119でボタンＢを押したとき。
![MC34119(I-17430)_ButtonB](https://github.com/algyan/XIAOGYAN/assets/135952435/018a3d04-64df-4b52-9df0-acd353804f2b)

**Comment by matsujirushi** [comment]
@yamati-kz 
すばらしい！確認ありがとうございます。

もし可能でしたら、[PlayWave](https://github.com/algyan/xiaogyan_examples/tree/main/platformio/PlayWave)も確認していただけませんか？（聴いた感じの比較で結構ですので）

**Comment by yamati-kz** [comment]
@matsujirushi 
聴いた感じ区別できません、私のような素人の耳では聞き分けできませんでした。
[PlayWave](https://github.com/algyan/xiaogyan_examples/tree/main/platformio/PlayWave)でのホワイトノイズの感じとか、とても可愛いお子ちゃまの声の感じとか、音量も違わないといいますか...

**Comment by yak1ex** [comment]
在庫復活しておりました。
MC34119も買っていましたので安心して使用できます。ありがとうございます。
